### ISSUE TITLE
Notification icon

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/notifications#629]
### Steps to reproduce
1. Delete all notifications.
2. Upgrade to the new version of Nextcloud 18.0.4 (manual update).

### Expected behaviour
No information next to the notification icon when no notifications are available.

### Actual behaviour
The notification icon indicates notification in the absence of notification.

![obraz](https://user-images.githubusercontent.com/47037905/80581934-34e7c080-8a0e-11ea-9e11-3b78c6e64703.png)

![obraz](https://user-images.githubusercontent.com/47037905/80582006-4c26ae00-8a0e-11ea-8701-d5a5b78db704.png)

**Nextcloud version:** (see Nextcloud admin page)
18.0.4 and 19.0.0beta5

**Comment by nickvergessen** [comment]
You were asked to approve notification permissions after clicking it, right?

**Comment by Valdnet** [comment]
@nickvergessen What permissions? You can explain more.

**Comment by Valdnet** [comment]
@nickvergessen Maybe the problem is only with a manual update. Because with automatic update from the Nextcloud admin panel, nextcloud notifications automatically appear when you enter a new instance.

**Comment by nickvergessen** [comment]
> ![Bildschirmfoto von 2020-04-29 14-17-20](https://user-images.githubusercontent.com/213943/80595022-56ec3d80-8a24-11ea-9a3d-86afabbb042f.png)

So when you didn't grant Permissions yet, you see a red dot also when you don't have any notifications and the menu then tells you that the permissions are missing.
When you accept or decline that once, it should work properly afterwards.

**Comment by Valdnet** [comment]
The problem is that after clicking the Nextcloud notification icon no browser message appears.

Web browser:
Firefox 75.0
System:
Win10

**Comment by nickvergessen** [comment]
So is this solved now after the rainloop issue?
Becuase it still works as expected here.

**Comment by Valdnet** [comment]
@nickvergessen There is still a problem with the notification markings described in this issue. The browser does not ask for notification permissions. Note that I also don't have the following information "Requesting browser permissions to show notifications" in the notification window and the notification icon has a lock marker.

> So is this solved now after the rainloop issue?

This was another problem already solved 😉.

**Comment by Valdnet** [comment]
@nickvergessen Only when the "Block new requests asking to allow notifications" option is selected in the browser is the notification icon displayed correctly. As if the function worked the other way around.

![image](https://user-images.githubusercontent.com/47037905/81927460-f6dcc600-95e3-11ea-9da0-c7131a8bc731.png)

**Comment by nickvergessen** [comment]
> "Blocking notifications may break some web site features"

it even specifically mentions it. Nothing we can do about it.

**Comment by Valdnet** [comment]
@nickvergessen You did not understand me :wink:.

In my opinion, the information about the lack of access to notifications (the red dot on the notification icon) works the other way around.

1. If the option in the browser is deselected.

![image](https://user-images.githubusercontent.com/47037905/81969881-ea299380-961e-11ea-8f52-fea1f80190a7.png)

- The notification icon indicates that the browser has blocked notifications.

![image](https://user-images.githubusercontent.com/47037905/81970014-2826b780-961f-11ea-8f2c-4f1f07f5cbbb.png)

- When you click the notification icon, the red dot disappears.

![image](https://user-images.githubusercontent.com/47037905/81970260-82277d00-961f-11ea-9585-2de2f868391b.png)

2. When checked, set the browser to block notifications.

![image](https://user-images.githubusercontent.com/47037905/81970374-bac75680-961f-11ea-82f7-72b79e6aa41d.png)

- The notification icon does not indicate that the browser has blocked notifications, but should.

![image](https://user-images.githubusercontent.com/47037905/81970465-e1858d00-961f-11ea-9dca-237097443bd4.png)
==
If I understood you correctly about this function, then it should work correctly this way:

1. Notification blocking function in browser not selected.

![image](https://user-images.githubusercontent.com/47037905/81969881-ea299380-961e-11ea-8f52-fea1f80190a7.png)

- Notification icon without red dot.

![image](https://user-images.githubusercontent.com/47037905/81970465-e1858d00-961f-11ea-9dca-237097443bd4.png)

2. Notification lock enabled in the browser.

![image](https://user-images.githubusercontent.com/47037905/81970374-bac75680-961f-11ea-82f7-72b79e6aa41d.png)

- The notification icon indicates that notifications are blocked (a red dot on the icon).

![image](https://user-images.githubusercontent.com/47037905/81970014-2826b780-961f-11ea-8f2c-4f1f07f5cbbb.png)

After clicking on the notifications icon should appear information like yours:

![image](https://user-images.githubusercontent.com/47037905/81971925-23173780-9622-11ea-925e-c1238cbfe0e3.png)

which is not displayed for me.

My information is only about no notifications.

![image](https://user-images.githubusercontent.com/47037905/81972066-56f25d00-9622-11ea-81d2-2a729186ff36.png)


I am asking you to analyze my observations. If you agree with them, please open the issue.

**Comment by Valdnet** [comment]
@nickvergessen After checking, I came to the conclusion that the described problem occurs when the page is not in the browser settings for notifications in:

![obraz](https://user-images.githubusercontent.com/47037905/82057357-82795400-96c3-11ea-99af-875695bbd6d3.png)

**Comment by shibotto** [comment]
Same problem up to 18.0.6, although I never get the red dot. It always worked fine until 18.0.4.

**Comment by shibotto** [comment]
It seems to be working again for me in 19.0.2 👍
(localized screenshot, sorry)
![Schermata da 2020-08-31 12-44-31](https://user-images.githubusercontent.com/3816409/91712328-d5e6b380-eb87-11ea-8fe8-98e30be61398.png)
